server:
    port: 8080
---
spring:
    profiles: dev
    datasource:
        platform: h2
        url: jdbc:h2:mem:cooperation;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
---
spring:
    profiles: prod
